config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :stores, only: [:index]
  resources :aboutuspages, only: [:index]
  resources :contactuspages, only: [:index]
  resources :gallerys, only: [:index]
  resources :reviews

  get '/services/pediatric'
  get '/services/index'

  root 'stores#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.nil?
        can :read, [Service,Review]
    elsif user.role? "admin"
        can :manage, :all 
    elsif user.role? "user"
        can :read, Service
        can [:create, :read], Review 
        can [:destroy,:update], Review do |review|
            review.try(:user) == user 
        end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :service
	belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base

	has_many :permissions
	has_many :users, through: :permissions
end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :reviews
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates_presence_of :username

         has_many :reviews

         has_many :permissions
         has_many :roles, through: :permissions

         after_create :generate_role

         def role?(role)
         	self.roles.pluck(:name).include? role 
         end

         def generate_role
         	Permission.create(user_id: self.id, role_id: Role.last.id)
         end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
        # Prevent CSRF attacks by raising an exception.
        # For APIs, you may want to use :null_session instead.
        protect_from_forgery with: :exception


        rescue_from CanCan::AccessDenied do 
  	       redirect_to root_path, alert: "You are not authorized to access this section"
  	end
end

app/controllers/gallerys_controller.rb
class GallerysController < ApplicationController
	def index
		#render action: "index"
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :authenticate_user!, except: [:index]
    load_and_authorize_resource
	def index 
		@reviews = Review.all
    end

    def new
    	@review = Review.new
    end

    def create
    	@review = Review.new(review_params)
    	@review.user_id = current_user.id
    	if @review.save
            redirect_to reviews_path, notice: "successfully created"
    	else
    		render action: "new"
    	end
    end

    def show
        @review = Review.find(params[:id])
    end

    def edit
		@review = Review.find(params[:id])
    end

    def update
        @review = Review.find(params[:id])
        if @review.save
                redirect_to reviews_path, notice: "successfully updated"
        else
            render action: "edit"
        end
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy
        #redirect_to service_path(@review.service_id), notice: "successfully destroyed"
        redirect_to reviews_path, notice: "successfully destroyed"
    end

    private

    def review_params
    	params[:review].permit(:service_id, :user_id, :comment, :rating)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

    def index
		@services=Service.all
		#@review = Review.new
		#@reviews = @service.reviews
	end

	def pediatric
	end

end	

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	def index
		#render action: "index"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/aboutuspages_helper.rb
module AboutuspagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactuspages_helper.rb
module ContactuspagesHelper
end

app/helpers/gallerys_helper.rb
module GallerysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reviews/_form.html.erb
<style>
      .progress{
    height: 10px;
    margin-top: 5px;
    margin-bottom: 5px;
} 
</style> 


<%= form_for @review do |f| %>
<% if @review.errors.any? %>
 <div class="alert alert-danger">
   <h3>These errors phohibitted the form from being saved: </h3>
   <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
   </ul>
  </div>
 <% end %>



<!-- .progress{
    height: 10px;
    margin-top: 5px;
    margin-bottom: 5px;
} -->

      <%# f.hidden_field :service_id, value: @service.id %>
<section id="blogArchive"> 
      <div class="form-group">
      <%= f.label :Comment %>
      <%= f.text_area :comment, class: "form-control" %><br/>
      </div>


      <div class="form-group">
      <%= f.label :rating%>

        <label class="radio-inline">
          <%= f.radio_button :rating, "1"%> 1 
        </label>

        <label class="radio-inline">
        <%= f.radio_button :rating, "2"%> 2 
        </label>



        <label class="radio-inline">
        <%= f.radio_button :rating, "3"%> 3
        </label>

        
        <label class="radio-inline">
        <%= f.radio_button :rating, "4"%> 4
        </label>

        <label class="radio-inline">
        <%= f.radio_button :rating, "4.5"%> 4.5
        </label>

        <label class="radio-inline">
        <%= f.radio_button :rating, "5"%> 5 <br/>
        </label><br/>

      <%= f.submit "Add the comment", class: "btn btn-info" %>
    
  <% end %> <br/>
</div>
</section>


















<!--  <div class="col-s-14">
 -->
    <!--

     Rating Widget 

    -->
    <!-- <div class="ui segment res-rating-widget mbot" style="">
        <div class="restaurant-rating-widget">
            <div class="review-rating-widget your-rating rating-widget rating-widget-res_51523" data-review_id="" data-rating-for="restaurant" data-res_id="51523">
                <div class="your-rating-info grey-text mbot0 ttupper bold" tabindex="0"></div>
                <div class="">
                    <div id="review-form" class="rating-widget-stars left mr10" data-za-intent="raterestaurant.post" data-za-event="click">
                        <div class="rating-cls user_stars2_0" data-rating="0" data-originalclass="user_starssel_0">

    <a class="level-1 level-0" data-original-title="1.0" data-hover-rating="1.0" data-num="2" href="#" aria-label="1.0"></a>

<a class="level-2 level-0" data-original-title="1.5" data-hover-rating="1.5" data-num="3" href="#" aria-label="1.5"></a>

<a class="level-3 level-0" data-original-title="2.0" data-hover-rating="2.0" data-num="4" href="#" aria-label="2.0"></a>

<a class="level-4 level-0" data-original-title="2.5" data-hover-rating="2.5" data-num="5" href="#" aria-label="2.5"></a>

<a class="level-5 level-0" data-original-title="3.0" data-hover-rating="3.0" data-num="6" href="#" aria-label="3.0"></a>

<a class="level-6 level-0" data-original-title="3.5" data-hover-rating="3.5" data-num="7" href="#" aria-label="3.5"></a>

<a class="level-7 big rating-sel level-0" data-original-title="4.0" data-hover-rating="4.0" data-num="8" href="#" aria-label="4.0"></a>

<a class="level-8 big level-0" data-original-title="4.5" data-hover-rating="4.5" data-num="9" href="#" aria-label="4.5"></a>

<a class="level-9 big bigger level-0" data-original-title="5.0" data-hover-rating="5.0" data-num="10" href="#" aria-label="5.0"></a>

                    </div>
                </div>
                <div class="rating-top pt5"></div>
                <div class="clear"></div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>

</div>-->
<!--

 /Rating Widget 

-->

<!--

 Review Textarea 

-->
<!--
<div class="clearfix mbot pos-relative" style="padding: 0;">

    ::before
    <div id="review-form-textarea-id" class="review-form-textarea right brtop" contenteditable="true" style="min-height: 100px; color: rgb(211, 211, 211);" aria-multiline="true" role="textbox"></div>

                                                        <div id="review-length-error-message"></div>
                                                        ::after
                                                    </div>-->
                                                    <!--

                                                     /Review Textarea 

                                                    -->
                                                    <!--

                                                     Blog URL 

                                                    -->
                                                    <!--

                                                     /Blog URL 

                                                    -->
                                                    <!--

                                                     Tags 

                                                    -->
                                                    <div class="row clearfix"></div>
                                                    <!--

                                                     /Tags 

                                                    -->
                                                    <!--
                                                    <div class="ui segment review-photos hidden " data-is_res_page="" data-review_id="0"></div>
                                                    

                                                     Footer 

                                                    
                                                    <div class="clearfix mtop0 row"></div>
                                                    <div class="review-form-error-message error-message-highlight hidden mtop0 ui error message"></div>
                                                    <div class="review-error-msg-container mtop review-err-msg hidden ui error message"></div>-->
                                                    <!--

                                                     /Footer 

                                                    -->
                                                    <!--
                                                </div>
                                                ::after
                                            </div>
                                        </div>
                                    </div>
                                    <div class="review-form-success-message error-message-highlight hidden mtop"></div>
                                    ::after
                                </div>
                                ::after
                            </div>
                        </div>
                    </div>
                    ::after
                </div>
            </div>
        </div>
    </div>

</div>
<div class="res-review-tab-content-container">

    <div class="res-review-tab-content activity-tab active">
        <div class="activity-feed-container">
            <div id="ipadding-reviews-box" class=" ipadding p-relative reviews res-review-form-container review_message_container">
                <div id="reviews-container" class="zs-load-more-container" data-filter="reviews-top">
                    <div class="notifications-content">
                        <div class="clearfix reviews-subhead pt15 ui segments white-bg mbi"></div>
                        <div class="res-reviews-container"></div>

<div class="res-reviews-container res-reviews-area">

    <div class="zs-following-list">
        <script type="application/javascript"></script>
        <div>
            <div class=" ui segments res-review-body res-review clearfix js-activity-root mbti item-to-hide-parent stupendousact" data-res_id="51523" data-snippet="restaurant-review" data-review_id="29823028">

        ::before
        <div class="ui segment clearfix br0 ">
            ::before
            <div class="review-header-text mbot0"></div>
            <div class="ui warning message error-message-highlight review-message hidden mbot"></div>
            <div class="ui item clearfix ">
                ::before
                <div class="item">
                    <div class="clearfix mb10 ">
                        ::before
                        <div class="res-large-snippet ui horizontal list col-s-16 ">
                            <div class="item col-s-16">
                                <a href="https://www.zomato.com/users/chandana-p-35408884"></a>
                                -->
                                <!--

                                      

                                -->
                                <!--z
                                <div class="content col-l-11 large-snippet ml5 mt5"></div>
                                ::after
                            </div>
                        </div>
                        ::after
                    </div>
                </div>
                <div class="fs12px pbot0 clearfix"></div>
                ::after
            </div>
            <div class="rev-text mbot0 " style="line-height: 20px;" tabindex="0"></div>
            <div class="photosContainer parentPhotoBox mtop0 mbot0 thumbsContainer"></div>
            <div id="restaurant_review_actions_29823028"></div>
            ::after
        </div>
        <div id="restaurant_review_owner_comment_thread_29823028"></div>
        <div id="restaurant_review_comment_thread_29823028"></div>
        ::after
    </div>

</div> -->

app/views/reviews/edit.html.erb
<div class="page-header">

</div>
	<div class= "row">
		<div class="col-md-6">
		<%= render 'form' %>
		</div>
	</div>

app/views/reviews/index.html.erb
<!-- BEGAIN PRELOADER -->
    <!-- <div id="preloader">
      <div id="status">&nbsp;</div>
    </div> -->
    <!-- END PRELOADER -->

<!-- Breadcrums start -->
<section id="blogArchive">      
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <div class="blog-breadcrumbs-area">
            <div class="container">
              <div class="blog-breadcrumbs-left">
                <h2>Reviews</h2>
              </div>
              <div class="blog-breadcrumbs-right">
                <ol class="breadcrumb">
                  
                  <li>You are here</li>
                   <li><a href="#">Home</a></li>                  
                  <li class="active">Reviews</li>
                </ol>
              </div>
            </div>
          </div>
        </div>        
      </div>      
</section>    
<!-- Breadcrums end -->

<div class="container">

      <% if user_signed_in? %>

          
          
            <%= link_to  new_review_path, class: "btn btn-primary btn-sm" do %>
              <i class="glyphicon glyphicon-plus "></i> Add Review
            <% end %>
           <strong> <button type="button" class="btn-xs pull-right"  >Welcome <%= current_user.username.capitalize %> Add Your Review</button></strong>
       <% else %>
<p class="bg-primary"></p>
       <!-- Trigger the modal with a button -->

<button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#myModal"> Add Your Review</button>  
</div>


<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <strong><h4 class="modal-title">Welcome To Neowomb</h4></strong>
      </div>
      <div class="modal-body", style="text-align:center">
       <!--  <h2><button type="button" class="btn btn-danger" data-dismiss="modal"><a href new_user_registration_path >Continue with Facebook</a></button></h2> -->
        <%= link_to  "http://www.facebook.com", class: "btn btn-primary " do %>Continue with Facebook
        <i class="glyphicon glyphicon-edit"></i> 
        <% end %><br/><br/>
        <%= link_to  "https://twitter.com", class: "btn btn-primary " do %>Continue with Twitter
        <i class="glyphicon glyphicon-edit"></i> 
        <% end %><br/><br/>
        <!-- Facebook Box Part Start-->
        <!-- <div id="facebook" class="part3">
        <h3>Join us on Facebook</h3>
        <div class="fb-page" data-href="http://www.facebook.com/dctacademy.bangalore" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"></div></div>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>
      </div> -->
              <!-- Facebook Box Part End-->
        <!-- Twitter Feeds Part Start-->
        <!-- <div id="twitter_footer" class="part3">
          <h3>Twitter Feed</h3>
          <div class="twitter_footer">
<a class="twitter-timeline" href="https://twitter.com/dct_academy" data-chrome="noheader nofooter noborders transparent" data-theme="dark" data-height="250"  data-related="twitterapi,twitter" data-aria-polite="assertive" data-widget-id="347621595801608192">Tweets by @harnishdesign</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>
        </div> -->
        <!-- Twitter Feeds Part End-->
        <!-- <p><button type="button" class="btn btn-info" data-dismiss="modal"><a href new_user_registration_path >Continue with Google</a></button></p>
        <h5>or</h5>
         <p style="text-align:center">Or use your email address</p> -->
      </div>
      <div class="modal-footer">
        <!-- <button type="button" class="btn btn-info" data-dismiss="modal"></button> -->
        <!-- <h4 class="modal-title"> <li><%# link_to "Registraion", new_user_registration_path %></li></h4>
         <h4 class="modal-title"> <li><%# link_to "Login", new_user_session_path %></li></h4> -->
        <!--  <h3> <button type="button" class="btn btn-info" data-dismiss="modal"><a href new_user_registration_path >Registration</a></button></h3>
          <h3><button type="button" class="btn btn-info" data-dismiss="modal"><a href new_user_session_path >Login</a></button></h3>
           <button type="button" class="btn btn-info" data-dismiss="modal"><%# link_to "Signup", new_user_registration_path %></button>
         <button type="button" class="btn btn-info"><span><li><%# link_to "Login", new_user_session_path %></li></span></button> -->
          <!-- <h4> <li><%# link_to "Signup", new_user_registration_path %></li>
           <li><%# link_to "Login", new_user_session_path %></li></h4> -->
          <!-- <strong> <p style="text-align:center">Or use your email address</p></strong> -->
           <%= link_to  new_user_session_path, class: "btn btn-primary btn-xs" do %>Login
                    <i class="glyphicon glyphicon-edit"></i> 
            <% end %>
            <%= link_to  new_user_registration_path, class: "btn btn-primary btn-xs" do %>Signup
                    <i class="glyphicon glyphicon-edit"></i> 
            <% end %>


<!-- <div class="col-md-10">
            <form class="button_to" method="get" action="/users/sign_in"> -->
            <!--  <input class="btn btn-info" type="submit" value="Login"> </form>-->
                <!-- <input class="btn btn-info" type="submit" data-toggle="modal" data-target="#myModal" value="Login">

           </form>  -->
           <!-- <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal"> -->

<!-- <div class="col-md-2">
             <form class="button_to" method="get" action="/users/sign_up">
                <input class="btn btn-info" type="submit" value="Signup"> 
            </form>
</div>
</div> -->



          
      </div>
    </div>
  </div>
</div>
<% end %>
        <strong>  <div class="page-header"></strong>
        
        
           <% @reviews.each do |review| %>
              <div class="thumbnail">
              <div class=container >

             <!-- Rating- <button type="button" class="btn btn-primary"><%= review.rating%>-</button>-<%= review.comment %> -->
             
             <strong>Rating <button type="button" class=" btn-xs"><%= review.rating%></button></strong>--<%= review.comment %><br/>
             <strong  class=" pull-right"  %>--------- <%= review.user.username.capitalize %> </strong><br/><br/>
              </div>
              <% if can? :update, review %>
                  <%= link_to  edit_review_path(review), class: "btn btn-primary btn-xs" do %>Edit Review
                    <i class="glyphicon glyphicon-edit"></i> 
                  <% end %>
              <% end %> 

            
                   <% if can? :destroy, review %> 
                      <%= link_to review_path(review), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-xs" do %>Delete Review
                          <i class="glyphicon glyphicon-trash"></i> 
                        <% end %><br/>
                  <% end %>
               </div> 
            <% end %>
       
      </div>
       

app/views/reviews/new.html.erb
<div class="page-header">

</div>
	<div class= "row">
		<div class="col-md-6">
		<%= render 'form' %>
		</div>
	</div>

app/views/stores/_counter.html.erb
<!--=========== BEGAIN Counter SECTION ================-->
    <section id="counterSection">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="counter-area">
              <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="counter-box">
                  <div class="counter-no counter">
                    200
                  </div>
                  <div class="counter-label">Doctors</div>
                </div>
              </div>
              <div class="col-lg-3 col-md-3 col-sm-6">
                 <div class="counter-box">
                  <div class="counter-no counter">
                    300
                  </div>
                  <div class="counter-label">Clinic Rooms</div>
                </div>
              </div>
              <div class="col-lg-3 col-md-3 col-sm-6">
                 <div class="counter-box">
                  <div class="counter-no counter">
                    350
                  </div>
                  <div class="counter-label">Awards</div>
                </div>
              </div>
              <div class="col-lg-3 col-md-3 col-sm-6">
                 <div class="counter-box">
                  <div class="counter-no counter">
                    450
                  </div>
                  <div class="counter-label">Happy Patients</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--=========== End Counter SECTION ================-->

app/views/stores/_service.html.erb
<!--=========== BEGIN Service SECTION ================-->
   <section id="service">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="service-area">
              <!-- Start Service Title -->
              <div class="section-heading">
                <h2>Our Services</h2>
                <div class="line"></div>
              </div>
              <!-- Start Service Content -->
              <div class="service-content">
                <div class="row">
                  <!-- Start Single Service -->
                  <div class="col-lg-4 col-md-4">
                    <div class="single-service">
                      <div class="service-icon">


                        <span class="fa fa-stethoscope service-icon-effect"></span>  
                      </div>                      
                      <h3><a href="<%= services_pediatric_path %>">Neonatal Team</a></h3>
                      <p>A Team of doctors is present in this Neonatal Team</p>
                    </div>
                  </div>
                  <!-- Start Single Service -->
                  <div class="col-lg-4 col-md-4">
                    <div class="single-service">
                      <div class="service-icon">
                      
                        <!-- <span class="fa fa-ambulance service-icon-effect"></span>  -->
                        <span class="fa fa-user-md service-icon-effect"></span> 
                      </div>                      
                      
                      <h3><a href="#">Pediatric Team</a></h3>
                      <p>Dr.Shekar<small>M.B.B.S,D.N.B,</small> and a Team of Pediatric doctors are present in this Pediatric Team</p>
                    </div>
                  </div>
                  <!-- Start Single Service -->
                  <div class="col-lg-4 col-md-4">
                    <div class="single-service">
                      <div class="service-icon">
                        <span class="fa fa-medkit service-icon-effect"></span>  
                      </div>                      
                      <h3><a href="#">Surgery Team</a></h3>
                      <p>Dr.Wasim<small>M.B.B.S,M.D</small>and a Team of Surgery doctors are present in this Surgery Team</p>
                    </div>
                  </div>
                  <!-- Start Single Service -->
                  <div class="col-lg-4 col-md-4">
                    <div class="single-service">
                      <div class="service-icon">
                        <span class="fa fa-h-square service-icon-effect"></span>  
                      </div>                      
                      <h3><a href="#">Dermatology</a></h3>
                      <p>Dr.Madhuri<small>M.B.B.S,M.D DVL,</small> Advanced Hair Transplantation, Skin & Laser Center and Consultant Dermatologist and Trichologist Clinical Dermatology</p>
                    </div>
                  </div>
                  <!-- Start Single Service -->
                  <div class="col-lg-4 col-md-4">
                    <div class="single-service">
                      <div class="service-icon">
                        <span class="fa fa-user-md service-icon-effect"></span>  
                      </div>                      
                      <h3><a href="#">Medical Team</a></h3>
                      <p>A Team of doctors is present in this Medical Team</p>
                    </div>
                  </div>
                  <!-- Start Single Service -->
                  <div class="col-lg-4 col-md-4">
                    <div class="single-service">
                      <div class="service-icon">
                        <span class="fa fa-ambulance service-icon-effect"></span>  
                      </div>                      
                      <h3><a href="#">Neonatal Emergency Service</a></h3>
                      <p>We are providing <br/>1.24/7 Ambulance Emergency Service,<br/>2.Vaccination Service,<br/>3.Mobile Laboratory Services,<br/>4.BloodBank,<br/>Mobile Blood Bank,<br/>5.Human Milk Bank,<br/>6.Well Baby Clinic,<br/>7.Mobile Laboratory Service </p>
                    </div>
                  </div>
                  <!-- Start Single Service -->
                 <!--  <div class="col-lg-4 col-md-4">
                    <div class="single-service">
                      <div class="service-icon">
                        <span class="fa fa-medkit service-icon-effect"></span>  
                      </div>                      
                      <h3><a href="#">MobileBloodBank&Counsilling</a></h3>
                      <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour</p>
                    </div>
                  </div> -->
                  <!-- Start Single Service -->
                  <!-- <div class="col-lg-4 col-md-4">
                    <div class="single-service">
                      <div class="service-icon">
                        <span class="fa fa-user-md service-icon-effect"></span>  
                      </div>                      
                      <h3><a href="#">WeelBabyClinics</a></h3>
                      <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour</p>
                    </div>
                  </div> -->
                  <!-- Start Single Service -->
                  <!-- <div class="col-lg-4 col-md-4">
                    <div class="single-service">
                      <div class="service-icon">
                        <span class="fa fa-ambulance service-icon-effect"></span>  
                      </div>                      
                      <h3><a href="#">BloodBanks&HumanMilkBank</a></h3>
                      <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour</p>
                    </div>
                  </div> -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--=========== End Service SECTION ================-->

app/views/stores/index.html.erb
<!-- BEGAIN PRELOADER -->
   <!--  <div id="preloader">
      <div id="status">&nbsp;</div>
      
    </div>  -->
    <!-- <div id="status">&nbsp;</div> -->
    <!-- END PRELOADER -->
    
<%= render 'slider' %>
<%= render 'featured' %>
<%= render 'service'%>
<%= render 'chooseus' %>
<%= render 'counter' %>
<%= render 'doctor' %>