config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :stores, only: [:index]
  resources :aboutuspages, only: [:index]
  resources :contactuspages, only: [:index]
  resources :gallerys, only: [:index]
  resources :reviews

  get '/services/pediatric'
  get '/services/index'

  root 'stores#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.nil?
        can :read, [Service,Review]
    elsif user.role? "admin"
        can :manage, :all 
    elsif user.role? "user"
        can :read, Service
        can [:create, :read], Review 
        can [:destroy,:update], Review do |review|
            review.try(:user) == user 
        end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :service
	belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base

	has_many :permissions
	has_many :users, through: :permissions
end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :reviews
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates_presence_of :username

         has_many :reviews

         has_many :permissions
         has_many :roles, through: :permissions

         after_create :generate_role

         def role?(role)
         	self.roles.pluck(:name).include? role 
         end

         def generate_role
         	Permission.create(user_id: self.id, role_id: Role.last.id)
         end

end

app/controllers/gallerys_controller.rb
class GallerysController < ApplicationController
	def index
		#render action: "index"
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :authenticate_user!, except: [:index]
    load_and_authorize_resource
	def index 
		@reviews = Review.all
    end

    def new
    	@review = Review.new
    end

    def create
    	@review = Review.new(review_params)
    	@review.user_id = current_user.id
    	if @review.save
            redirect_to reviews_path, notice: "successfully created"
    	else
    		render action: "new"
    	end
    end

    def show
        @review = Review.find(params[:id])
    end

    def edit
		@review = Review.find(params[:id])
    end

    def update
        @review = Review.find(params[:id])
        if @review.save
                redirect_to reviews_path, notice: "successfully updated"
        else
            render action: "edit"
        end
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy
        #redirect_to service_path(@review.service_id), notice: "successfully destroyed"
        redirect_to reviews_path, notice: "successfully destroyed"
    end

    private

    def review_params
    	params[:review].permit(:service_id, :user_id, :comment, :rating)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
	def index
		#render action: "index"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/aboutuspages_helper.rb
module AboutuspagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactuspages_helper.rb
module ContactuspagesHelper
end

app/helpers/gallerys_helper.rb
module GallerysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!--=========== Start Footer SECTION ================-->
    <footer id="footer">
      <!-- Start Footer Top -->
      <div class="footer-top">
        <div class="container">
          <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-3">
              <div class="single-footer-widget">
                <div class="section-heading">
                <h2>About Us</h2>
                <div class="line"></div>
              </div>           
              <p>NICU in partnership with SURAKSHA KIDZ HOSPITAL,REDDY AND REDDY'S COLONY. Our mission is to give quality service to the people.It is a long established fact by Dr.Shuba Shekar Reddy</p>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3">
              <div class="single-footer-widget">
                <div class="section-heading">
                <h2>Our Service</h2>
                <div class="line"></div>
              </div>
              <ul class="footer-service">
                <li><a href="#"><span class="fa fa-check"></span>Service 1</a></li>
                <li><a href="#"><span class="fa fa-check"></span>Service 2</a></li>
                <li><a href="#"><span class="fa fa-check"></span>Service 3</a></li>
                <li><a href="#"><span class="fa fa-check"></span>Service 4</a></li>
                <li><a href="#"><span class="fa fa-check"></span>Service 5</a></li>
                <li><a href="#"><span class="fa fa-check"></span>Service 6</a></li>
              </ul>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3">
              <div class="single-footer-widget">
                <div class="section-heading">
                <h2>Tags</h2>
                <div class="line"></div>
              </div>
                <ul class="tag-nav">
                  <li><a href="#">Neonatal Team</a></li>
                  <li><a href="#">Pediatric Team</a></li>
                  <li><a href="#">Surgery Team</a></li>
                  <li><a href="#">Dermatology</a></li>
                  <li><a href="#">Medical Team</a></li>
                  <li><a href="#">Neonatal Emergency Service</a></li>
                </ul>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3">
              <div class="single-footer-widget">
                <div class="section-heading">
                <h2>Contact Info</h2>
                <div class="line"></div>
              </div>
              <p>NICU in partnership with SURAKSHA KIDZ HOSPITAL,REDDY AND REDDY'S COLONY</p>
              <address class="contact-info">
                <p><span class="fa fa-home"></span>Mopuri SHUBA SHEKAR REDDY,S/O M SUBBA REDDY,Flat No-D 206,Sri Chakara Eden Greens Apartments, Upadyaya Nagar, Tirupati,Andhra Pradesh-517501</p>
                <p><span class="fa fa-phone"></span>9036959536,7989742875,9591621772</p>
                <p><span class="fa fa-envelope"></span>neowomb@gmail.com,doctorshekar@gmail.com</p>
              </address>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Start Footer Middle -->
      <div class="footer-middle">
        <div class="container">
          <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="footer-copyright">
              <p>&copy; Copyright 2015 <a href="index.html">Neowomb</a></p>
            </div>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="footer-social"> 
                         
                <a href="http://www.facebook.com"><span class="fa fa-facebook"></span></a>
                <a href="https://twitter.com"><span class="fa fa-twitter"></span></a>
                <a href="https://google.com"><span class="fa fa-google-plus"></span></a>
                <a href="https://linkedin.com"><span class="fa fa-linkedin"></span></a>     
            </div>
          </div>
        </div>
        </div>
      </div>
      <!-- Start Footer Bottom -->
      <div class="footer-bottom">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <p>Design & Developed By <a rel="nofollow" >Ishu</a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!--=========== End Footer SECTION ================-->

app/views/layouts/_navigation.html.erb
   <!--last one of navigation start -->
 <!--=========== BEGIN HEADER SECTION ================-->
    <header id="header">
      <!-- BEGIN MENU -->
      <div class="menu_area">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">  
          <div class="container">
           <a class="navbar-brand" href="#"><span><h1><strong>Neowomb</strong></h1></span>
               </a><br/><br/> 
           <% if user_signed_in? %>
            <div class="navbar-header">
              <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <!-- LOGO -->              
              <!-- TEXT BASED LOGO -->
              
              
               

              <!-- IMG BASED LOGO  -->
              <!--  <a class="navbar-brand" href="index.html"><img src="images/logo.png" alt="logo"></a>   -->                    
            </div>
            <div id="navbar" class="navbar-collapse collapse">
            
              <ul id="top-menu" class="nav navbar-nav navbar-right main-nav">
                      <!-- <a class=" pull-right"  %><%# review.user.username.capitalize %> </strong><br/><br/> -->
                      <li><a href="/">Home</a></li>
                      <li><a href="<%= aboutuspages_path %>">ABOUT US</a></li>
                      <li><a href="<%= services_path %>">SERVICES</a></li>
                      <li><a href="<%= gallerys_path %>">Gallery</a></li>
                      <li><a href="<%= contactuspages_path %>">Contact</a></li>
                      <li><a href="<%= reviews_path %>">Reviews</a></li>      
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Logout <span class="fa fa-angle-down"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Account Setting", edit_user_registration_path %> </li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>  </li>
                  </ul>
                </li>
              </ul>           
            </div><!--/.nav-collapse -->
            <% else %>

            <div class="navbar-header">
              <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <!-- LOGO -->              
              <!-- TEXT BASED LOGO -->
              <!--   <a class="navbar-brand" href="#"><span><h1><strong>Neowomb</strong></h1></span>
               </a><br/><br/>     -->      
              <!-- IMG BASED LOGO  -->
              <!--  <a class="navbar-brand" href="index.html"><img src="images/logo.png" alt="logo"></a>   -->                    
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul id="top-menu" class="nav navbar-nav navbar-right main-nav">
                      <li><a href="/">Home</a></li>
                      <li><a href="<%= aboutuspages_path %>">ABOUT US</a></li>
                      <li><a href="<%= services_index_path %>">SERVICES</a></li>
                      <li><a href="<%= gallerys_path %>">Gallery</a></li>
                      <li><a href="<%= contactuspages_path %>">Contact</a></li>
                      <li><a href="<%= reviews_path %>">Reviews</a></li>       
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Login <span class="fa fa-angle-down"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <!-- <button type="button" class="btn btn-default btn-lg" data-toggle="modal"  data-target="#ishu">Log in</button> 
                    <button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#signUp">Signup</button> -->
                    <li><%= link_to "Login", new_user_session_path %></li>
                    <li><%= link_to "Signup", new_user_registration_path %></li> 
                  </ul>
                </li>
              </ul>           
            </div><!--/.nav-collapse -->
            
            <% end %>
          </div>     
        </nav>  
      </div>
      <!-- END MENU -->  

   
    </header>
    <!--=========== END HEADER SECTION ================-->   



   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <!-- <link rel="shortcut icon" type="image/icon" href="images/favicon.ico"/> -->
    <!-- Mobile Specific Metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Pediatric Health Care center">
    <meta name="author" content="NEOWOMB HEALTH CARE PRIVATE LIMITED"> 
  
    <!-- Basic Page Needs
    ================================================== -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--  <title>NeoWombHealthCarePvtLtd</title> -->
     <title>NeoWombHealthCarePvtLtd</title>
    <!-- Mobile Specific Metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

 <!--    <%# stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 -->
    
    <%= stylesheet_link_tag    'application' %>

    <!-- Favicon -->
    <link rel="shortcut icon" type="images/icon" href="../images/favicon.ico"/>



    <!--JS Files Loading -->
    
    <!-- jQuery Library  -->
    <script src="/js/jquery.js"></script>    
    <!-- Bootstrap default js -->
    <script src="/js/bootstrap.min.js"></script>
    <!-- Photo Swipe Gallery Slider -->
    <script src="js/photoswipe-gallery.js"></script>
    <script src='/js/photoswipe.min.js'></script>
    <script src='js/photoswipe-ui-default.min.js'></script>    
    

      <!-- slick slider -->
    <script src="/js/slick.min.js"></script>    
    <script type="text/javascript" src="/js/modernizr.custom.79639.js"></script>    
    <!-- counter -->
    <script src="/js/waypoints.min.js"></script>
    <script src="/js/jquery.counterup.min.js"></script>
    <!-- Doctors hover effect -->
    <script src="/js/snap.svg-min.js"></script>
    <script src="/js/hovers.js"></script>
    <script src="/js/custom.js"></script>
   
    
    <!-- Custom JS -->
    
    <!--JS Files Loading-->
    
    
    <!-- CSS
    ================================================== -->       
    <!-- Bootstrap css file-->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- Font awesome css file-->
    <link href="css/font-awesome.min.css" rel="stylesheet">       
    <!-- Default Theme css file -->
    <link id="switcher" href="css/themes/default-theme.css" rel="stylesheet">    
    <!-- Slick slider css file -->
    <link href="css/slick.css" rel="stylesheet"> 

    <!-- Main structure css file -->
    <link href="style.css" rel="stylesheet">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

        <!-- Google Fonts (Droid Sans) Start -->
<link href='//fonts.googleapis.com/css?family=Droid+Sans&v1' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=&v1' rel='stylesheet' type='text/css'>
<!-- Google Fonts (Droid Sans) End -->

   <!-- <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
    <!--<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="Online e-commerce store">
  <meta name="author" content="DCT Academy"> -->
  <%# stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
   
 


  <%= csrf_meta_tags %>
</head>
<body>


	
	<!-- BEGAIN PRELOADER -->
    <!-- <div id="preloader">
      <div id="status">&nbsp;</div>
    </div> -->
    <!-- END PRELOADER -->

    <!-- SCROLL TOP BUTTON -->
    <a class="scrollToTop" href="#"><i class="fa fa-heartbeat"></i></a>
    <!-- END SCROLL TOP BUTTON -->

    <%= render '/layouts/navigation' %>



    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

	<%= yield %>
	<%= render '/layouts/footer' %>

    
    <%= javascript_include_tag 'application' %> 
<!-- 	<%# javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
</body>
</html>